#Search Microservice
search:
  image:elasticsearch
  ports:
    -9200:9200
    -9300:9300

#Search Microservice
search-service:
  build:../search-service
  links:
    -search
  volumes:
    -log

#Editor Service Database
mongo-edit:
  image:mongo
  links:
    -search
  volumes:
    -data

#Editor Microservice
editor-service:
  build:../editor-services
  links:
    -mongo-edit:db
  volumes:
    -log

#Api-Gateway Database
mongo-api:
  image:mongo
  volumes:
    -data

#Authentication, Authorization and Reverse Proxy
api-gateway:
  build:../api-gateway
  ports:
    -8080:8080
  volumes:
    -log
  links:
    -mongo-api:db
    -editor-gateway:editor
    -serach-service:search
